export const SEQUELIZE = 'SEQUELIZE';
export const PROCESS_REPOSITORY = 'PROCESS_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const QUEUE_REPOSITORY = 'QUEUE_REPOSITORY';
export const DATA_SOURCE = 'DATA_SOURCE';
