export const SEQUELIZE = 'SEQUELIZE';
export const PROCESS_REPOSITORY = 'PROCESS_REPOSITORY';
export const PROCESS_REPOSITORY_ORM = 'PROCESS_REPOSITORY_ORM';
export const DATA_SOURCE = 'DATA_SOURCE';
